# This file contains the fastlane.tools configuration
# https://docs.fastlane.tools

default_platform(:android)

platform :android do
  desc "Runs unit tests"
  lane :test do
    gradle(task: "testFossDebugUnitTest")
  end
end
